In [9]:
# Import All Libraries Here
import pandas as pd
from sklearn.linear_model import LogisticRegression 
import numpy as np

In [3]:
#Read X Varaibles and Y Varaibles
train_rna_x_varaibles =  pd.read_csv("../data/train_in.csv")
train_rna_y_varaibles =  pd.read_csv("../data/train_out.csv")

In [26]:
# Encode using one-hot encoding 

def apply_one_hot_encode(sequence):
    nucleotides = ['C', 'A', 'T', 'G']
    one_hot = []
    for nucleotide in sequence:
        # For G - [0,0,1,0]
        if nucleotide == 'N': # N is not application , used for empty values.
            hot = [0,0,0,0]
        else:
            hot = [0 if nucleotide != nt else 1 for nt in nucleotides]

        one_hot.append(hot)
    return one_hot

train_rna_x_varaibles_encoded = train_rna_x_varaibles.apply(apply_one_hot_encode, axis=1)

train_rna_x_varaibles_encoded.head(3)

In [25]:
x = np.array(train_rna_x_varaibles_encoded)
y = np.array(train_rna_y_varaibles)

print(y)

logreg = LogisticRegression()
logreg.fit(train_rna_x_varaibles_encoded, y)


[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


ValueError: setting an array element with a sequence.